package org.ecs160.a2;


import static com.codename1.ui.CN.*;

import com.codename1.components.MultiButton;
import com.codename1.ui.*;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;

import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class AppMain {

    private Form current;
    private Resources theme;
    private Object Center;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }

    public void start() {
        if(current != null){
            current.show();
            return;
        }
        ShowArchivePage();
        //Form hi = new Form("Hi World", BoxLayout.y());
        //hi.add(new Label("Hi World"));
        //Button b = new Button("My Button");
        //b.addActionListener((e)->Func());
        //hi.add(b);
        //hi.show();
    }

    public void ShowArchivePage(){
        //https://www.youtube.com/watch?v=0m7Bay4g93k&t=114s
        System.out.println("Showing the Archive Page");
        Form newForm = new Form("Archive Page", BoxLayout.y());
        newForm.getToolbar().addCommandToLeftBar("Done", null, (e)->Log.p("Clicked"));
        newForm.getToolbar().addCommandToRightBar("Filter", null, (e)->Log.p("Filter Clicked"));
        TextField SearchBar = new TextField("", "Search", 20, TextArea.ANY);
        newForm.add(SearchBar);
        Container List = new Container(BoxLayout.y());
        List.setScrollableY(true);
        for (int i = 0; i < 1000 ; i++){
            MultiButton mb = new MultiButton("List Entry " + i);
            mb.setTextLine2("Further details...");
            List.add(mb);
        }
        newForm.add(Center, List);
        newForm.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
